export const telegram = 'https://t.me/Sergey_Designer';
export const channel = 'https://t.me/soc_blog';
export const store = 'https://www.rustore.ru/catalog/app/app.lingoslide';
export const messageLink = (text) => `${telegram}?text=${encodeURIComponent(text)}`;
export const content = {
  ru: {
    brand: ['Серёга —', 'есть идея!'], name: 'Сергей Остаев', nav: ['Проекты', 'Подход', 'Обо мне', 'Резюме', 'Вместе'], menu: 'Открыть меню', close: 'Закрыть меню', skip: 'К содержанию',
    idea: 'Есть идея?', see: 'Смотреть проекты', discuss: 'Обсудить идею', back: 'Все проекты', read: 'Открыть кейс',
    hero: ['Больше,', 'чем идеи.'], lead: 'Придумываю, собираю и запускаю цифровые продукты',
    intro: 'Помогаю командам и людям превратить «а что, если…» в работающую вещь — от первого разговора до запуска',
    note: 'Давай сделаем\nчто-нибудь настоящее.', portrait: 'Сергей Остаев, автор цифровых продуктов', caption: 'Тот самый человек, которому можно принести идею',
    proof: [['9+', 'продуктов и сервисов'], ['5', 'специалистов в команде'], ['IT Camp ’25', 'проект для Газпром нефти']],
    nowLabel: '01 / В РАБОТЕ', nowTitle: 'Идеи обретают форму.', nowText: 'Запускаю своё, пробую новое и показываю, на каком этапе каждый проект.',
    lingoDesc: 'Полноценная система изучения английского, которую я спроектировал и довёл до релиза.', own: 'СОБСТВЕННЫЙ ПРОДУКТ', storeLabel: 'Открыть в RuStore',
    nowRows: [
      {name:'LingoSlide',desc:'Образовательный продукт для Android',status:'SHIPPED',detail:'Я продумал продукт, учебную логику и все взаимодействия, отрисовал интерфейс и довёл версию 1.1.0 до релиза.',href:'/case/lingoslide',icon:'book'},
      {name:'Scooter Game',desc:'Эксперимент с игровой механикой',status:'BUILDING',detail:'Собираю 2D-игру про самокат. Исследую, как превратить простое действие в интересный игровой цикл.',icon:'bolt'},
      {name:'Личные финансы',desc:'Ищу удобный способ понимать свои деньги',status:'EXPLORING',detail:'Проверяю идею помощника для личных финансов. Сейчас — вопросы, сценарии и поиск полезного первого шага.',icon:'wallet'},
      {name:'AiZooFamily',desc:'Вселенная персонажей · 30 000+ показов',status:'PAUSED',detail:'Проект сейчас на паузе, но Pinterest продолжает приносить не менее 30 000 показов. Я создавал персонажей, визуальную вселенную и контент-систему, а затем остановил активное производство, когда оно стало забирать слишком много ресурсов.',href:'https://pinterest.com/AiZooFamily/',external:true,icon:'pause'}
    ],
    processLabel: '02 / ПОДХОД', processTitle: 'От «а что, если» до «уже работает»',
    steps: [ ['Понимаю','Что болит, кому это нужно и как выглядит полезный результат','comments'], ['Придумываю','Выбираю главный сценарий и превращаю идею в понятное решение','lightbulb'], ['Собираю','Делаю прототип, проверяю логику и подключаю нужные инструменты','box'], ['Запускаю','Прохожу проверки, довожу до релиза и смотрю, что улучшить','send'] ],
    workLabel:'03 / ИЗБРАННОЕ', workTitle:'За каждой работой — задача', workText:'Собственные продукты, корпоративные системы и решения в сложных предметных областях', archive:'Дизайн-архив',
    projects:[
      {id:'enterprise',tag:'BIG TECH / TELECOM · NDA / LEADERSHIP',ndaLabel:'АНОНИМИЗИРОВАНО ПОД NDA',title:'Из сложного процесса — в понятную систему.',name:'Enterprise Automation',desc:'Роли, сценарии и автоматизация внутренних процессов. От разбора задачи до работы с командой внедрения.'},
      {id:'rag',tag:'BIG TECH / TELECOM · NDA / AI / KNOWLEDGE',ndaLabel:'АНОНИМИЗИРОВАНО ПОД NDA',title:'Знания компании, с которыми можно говорить.',name:'RAG Platform',desc:'Поиск по корпоративным знаниям: понятный ответ, источник и контроль доверия к AI.'},
      {id:'igms',tag:'PRODUCT / CONCEPT',title:'Весь контекст. Один диалог.',name:'iGMS',desc:'Концепция единого inbox для управления недвижимостью. Переписка, бронирования и AI-подсказки.'},
      {id:'diagnostics',tag:'INDUSTRIAL AI / IT CAMP 2025',title:'Разобраться в сложном. Успеть собрать.',name:'AI Diagnostics',desc:'Продуктовое решение для промышленной диагностики на IT Camp в Сириусе.'}
    ],
    storyLabel:'СВОЙ ПРОДУКТ / LINGOSLIDE', storyTitle:'Я продумал продукт.\nИ довёл его до релиза.', storyText:'От личной задачи до LingoSlide 1.1.0: продуктовая концепция, образовательная система, все пользовательские сценарии, UX/UI, локализация и контроль качества.', storyCta:'Разобрать весь кейс', storyFacts:[['34 дня','до второй версии'],['16','языковых направлений'],['240 / 240','тестов прошли']],
    aboutLabel:'04 / ЧЕЛОВЕК ЗА ПРОЕКТАМИ', aboutTitle:'Привет, я Серёга.', aboutLead:'Люблю момент, когда разрозненные мысли вдруг складываются в работающую вещь.',
    aboutText:'Мой путь — от продуктовой логики и внутренних IT-систем до автоматизации, AI-продуктов и собственных запусков. Работал в X5 Tech и Ростелеком ИТ, координировал команду из пяти специалистов. Соединяю людей, решения и инструменты, чтобы идея дошла до результата.', aboutNote:'Любопытство —\nмой рабочий инструмент.', resume:'Опыт подробнее', cameraAlt:'Сергей с камерой: личная фотография',
    cvLabel:'05 / РЕЗЮМЕ',cvTitle:'Опыт — в одном файле.',cvText:'Две актуальные версии резюме. Выберите удобный язык и скачайте PDF.',cvRu:'Резюме на русском',cvEn:'CV in English',cvPages:'страницы',cvMore:'Посмотреть опыт на сайте',
    waysLabel:'06 / СДЕЛАЕМ ВМЕСТЕ', waysTitle:'Можно начать\nс одной мысли.', waysText:'Необязательно иметь готовое ТЗ. Расскажи, что хочется изменить, — найдём первый практический шаг.',
    ways:[['Разбор идеи','Есть мысль, но пока нет ясности. Разберём задачу, ограничения и решим, что проверять первым.','Понятный следующий шаг','comments'],['Product Sprint','Нужно увидеть, как идея будет работать. Соберём ключевой сценарий и прототип для проверки.','От задачи до прототипа','bolt'],['Менторство','Есть проект, портфолио или желание запустить своё. Помогу увидеть точки роста и составить план.','Обратная связь и движение','users'],['Партнёрство','Ищешь человека, который включится в продукт целиком. Обсудим роли, ценность и совместную работу.','Общее дело','compass']],
    labLabel:'IDEA LAB / ЗАМЕТКИ ПО ПУТИ', labTitle:'Показываю, как получается.', labText:'Идеи, эксперименты, решения и то, что пришлось переделать. Продолжение истории — в Telegram.', labCta:'Заглянуть в мастерскую',
    contactTitle:'Есть идея?', contactText:'Давай дадим ей шанс.', contactHint:'Начни с пары предложений. Можно без презентации.', contactCta:'Написать Серёге', email:'Или на почту', location:'Самара. Работаю удалённо.', footer:'От первой мысли до работающего продукта.', top:'Наверх',
    caseLabel:'СОБСТВЕННЫЙ ПРОДУКТ / ANDROID', caseTitle:'LingoSlide — продуктовый дизайн и запуск', caseLead:'Кейс о том, как я продумал продукт, спроектировал учебную логику и все взаимодействия, отрисовал интерфейс и довёл LingoSlide 1.1.0 до релиза.',
    caseSections:[
      ['01 / ОТПРАВНАЯ ТОЧКА','Хотелось регулярно учить слова.','Нам не хватало простого способа увеличивать словарный запас. Задача была конкретной: учить новые слова, отмечать знакомые и возвращаться к сложным. Отсюда выросла идея отдельного тренажёра.'],
      ['02 / ПРОДУКТОВАЯ ЛОГИКА','Небольшое действие. Понятный прогресс.','В основе — 5000 слов от A1 до C1, карточки с переводом и примерами, отметки «знаю / не знаю». Сложные слова возвращаются на повторение, а дополнительные режимы помогают менять темп практики.'],
      ['03 / МОЯ РОЛЬ','Собрать весь путь, а не один экран.','Я отвечал за идею, продуктовую логику, UX, визуальное направление и организацию разработки с AI. Дальше — проверка сценариев, подготовка Android-релиза и публикация. Решения по продукту оставались за мной; AI помогал их реализовать.'],
      ['04 / AI В ПРОЦЕССЕ','Использовать инструмент там, где он полезен.','Codex помогал с разработкой и процессом локализации: интерфейсными строками, словарём и согласованностью изменений. Важная часть работы — проверять результат в приложении и возвращаться к ошибкам.'],
      ['05 / ЗАПУСК','Пройти дальше прототипа.','В RuStore опубликовано Android-приложение: изучение и повторение слов, избранное, Speed Run и сохранение прогресса. Приложением можно пользоваться без обязательной регистрации.'],
      ['06 / ЧТО ДАЛЬШЕ','Улучшать то, чем действительно пользуются.','Следующий этап — собирать обратную связь, проверять сложные места в обучении и постепенно развивать сценарии. Самое ценное в этом проекте — возможность пройти весь путь и отвечать за каждое решение.']
    ], screenshots:'Настоящие экраны приложения из RuStore', next:'Обсудим твой продукт?', imageAlt:'Промоэкран LingoSlide из RuStore',
    statusLabels:{SHIPPED:'Запущен',BUILDING:'В разработке',EXPLORING:'Исследую',PAUSED:'На паузе'},
  },
  en: {
    brand:['Sergey —','got an idea!'], name:'Sergey Ostaev',nav:['Projects','Approach','About','CV','Work together'],menu:'Open menu',close:'Close menu',skip:'Skip to content',idea:'Got an idea?',see:'Explore projects',discuss:'Let’s talk',back:'All projects',read:'Read the story',
    hero:['Beyond','ideas.'],lead:'I imagine, build and launch digital products',intro:'I help people and teams turn “what if…” into something that works — from the first conversation to launch',note:'Let’s make\nsomething real.',portrait:'Sergey Ostaev, digital product builder',caption:'The person you can bring your idea to',
    proof:[['9+','products and services'],['5','specialists coordinated'],['IT Camp ’25','project for Gazprom Neft']],
    nowLabel:'01 / IN PROGRESS',nowTitle:'Ideas taking shape.',nowText:'Building my own products, trying new things and sharing where each project stands.',lingoDesc:'A complete English learning system I designed and took through release.',own:'OWN PRODUCT',storeLabel:'View on RuStore',
    nowRows:[
      {name:'LingoSlide',desc:'An English learning product for Android',status:'SHIPPED',detail:'I designed the product, learning logic and every interaction, created the interface and shipped version 1.1.0.',href:'/case/lingoslide',icon:'book'},
      {name:'Scooter Game',desc:'An experiment with game mechanics',status:'BUILDING',detail:'Building a 2D scooter game. Exploring how a simple action becomes a compelling gameplay loop.',icon:'bolt'},
      {name:'Personal Finance',desc:'A clearer way to understand money',status:'EXPLORING',detail:'Exploring a personal finance assistant. Right now: questions, scenarios and a useful first step.',icon:'wallet'},
      {name:'AiZooFamily',desc:'Character universe · 30K+ impressions',status:'PAUSED',detail:'The project is currently paused, but Pinterest still generates at least 30K impressions. I built the characters, visual universe and content system, then paused active production when the resource cost became too high.',href:'https://pinterest.com/AiZooFamily/',external:true,icon:'pause'}
    ],
    processLabel:'02 / APPROACH',processTitle:'From “what if” to “it works”',steps:[['Understand','The problem, the people and what a useful outcome looks like','comments'],['Imagine','Choose the core scenario and turn the idea into a clear solution','lightbulb'],['Build','Make a prototype, test the logic and bring in the right tools','box'],['Launch','Test, ship and find what to improve next','send']],
    workLabel:'03 / SELECTED WORK',workTitle:'A real problem behind every project',workText:'Independent products, enterprise systems and solutions in complex domains',archive:'Design archive',
    projects:[
      {id:'enterprise',tag:'BIG TECH / TELECOM · NDA / LEADERSHIP',ndaLabel:'ANONYMIZED UNDER NDA',title:'Complex processes. Clear systems.',name:'Enterprise Automation',desc:'Roles, scenarios and internal automation. From understanding the problem to collaborating with the delivery team.'},
      {id:'rag',tag:'BIG TECH / TELECOM · NDA / AI / KNOWLEDGE',ndaLabel:'ANONYMIZED UNDER NDA',title:'Company knowledge you can talk to.',name:'RAG Platform',desc:'Enterprise knowledge search with clear answers, visible sources and trust in AI.'},
      {id:'igms',tag:'PRODUCT / CONCEPT',title:'Every detail. One conversation.',name:'iGMS',desc:'A unified inbox concept for property management. Messages, bookings and AI assistance.'},
      {id:'diagnostics',tag:'INDUSTRIAL AI / IT CAMP 2025',title:'Understand complexity. Build quickly.',name:'AI Diagnostics',desc:'An industrial diagnostics product solution developed at IT Camp in Sirius.'}
    ],
    storyLabel:'OWN PRODUCT / LINGOSLIDE',storyTitle:'I designed the product.\nThen I shipped it.',storyText:'From a personal need to LingoSlide 1.1.0: product concept, learning system, every user flow, UX/UI, localization and release quality.',storyCta:'Explore the full case',storyFacts:[['34 days','to version two'],['16','language tracks'],['240 / 240','tests passed']],
    aboutLabel:'04 / THE PERSON BEHIND THE WORK',aboutTitle:'Hi, I’m Sergey.',aboutLead:'I love the moment when scattered thoughts turn into something that works.',aboutText:'My path runs from product logic and internal IT systems to automation, AI and independent products. I worked at X5 Tech and Rostelecom IT, coordinating a team of five specialists. I connect people, decisions and tools to bring ideas to life.',aboutNote:'Curiosity is\npart of the job.',resume:'Explore my experience',cameraAlt:'Sergey with a camera, a personal photo',
    cvLabel:'05 / CV',cvTitle:'The experience, in one file.',cvText:'Two current versions of my CV. Choose your language and download the PDF.',cvRu:'Резюме на русском',cvEn:'CV in English',cvPages:'pages',cvMore:'Explore my experience online',
    waysLabel:'06 / WORK TOGETHER',waysTitle:'One thought\nis a good start.',waysText:'You don’t need a finished brief. Tell me what you want to change, and we’ll find a practical first step.',ways:[['Idea review','An idea without a clear direction? We’ll explore the problem, constraints and what to test first.','A clear next step','comments'],['Product Sprint','See how your idea could work. We’ll build the core scenario and a prototype to test.','From problem to prototype','bolt'],['Mentoring','A project, a portfolio or the ambition to launch something. I’ll help identify opportunities and make a plan.','Feedback and progress','users'],['Partnership','Looking for someone to get involved across the product? Let’s discuss roles, value and working together.','Something we build together','compass']],
    labLabel:'IDEA LAB / NOTES ALONG THE WAY',labTitle:'Sharing the making of it.',labText:'Ideas, experiments, decisions and things I had to rethink. Follow the story on Telegram.',labCta:'Visit the workshop',contactTitle:'Got an idea?',contactText:'Let’s give it a chance.',contactHint:'A couple of sentences is enough. No pitch deck needed.',contactCta:'Talk to Sergey',email:'Or send an email',location:'Samara. Working remotely.',footer:'From a first thought to a working product.',top:'Back to top',
    caseLabel:'OWN PRODUCT / ANDROID',caseTitle:'LingoSlide — product design and launch',caseLead:'A case study of how I defined the product, designed its learning logic and every interaction, created the interface and took LingoSlide 1.1.0 through release.',
    caseSections:[['01 / THE START','We wanted to learn words consistently.','We needed a simple way to grow our vocabulary: learn new words, mark familiar ones and return to difficult ones. That specific need became the starting point for a dedicated trainer.'],['02 / PRODUCT LOGIC','A small action. Visible progress.','The core includes 5,000 words across A1–C1, flashcards with translations and examples, and “know / don’t know” actions. Difficult words return for review; extra practice modes change the pace.'],['03 / MY ROLE','Build the whole journey.','I owned the idea, product logic, UX, visual direction and coordination of AI-assisted development. Then came scenario checks, Android release preparation and publishing. I made product decisions; AI helped implement them.'],['04 / AI IN THE PROCESS','Use the tool where it helps.','Codex supported development and localization workflows: interface strings, vocabulary and consistent changes. An essential part was checking the results in the app and fixing mistakes.'],['05 / RELEASE','Beyond the prototype.','The Android app is published on RuStore with word learning and review, favourites, Speed Run and saved progress. It can be used without mandatory registration.'],['06 / WHAT’S NEXT','Improve what people actually use.','The next step is gathering feedback, finding friction in learning and developing useful scenarios. The value of this project is owning the whole journey and every decision along the way.']],screenshots:'Actual app promotional screens from RuStore',next:'Let’s talk about your product.',imageAlt:'LingoSlide promotional screen from RuStore',statusLabels:{SHIPPED:'Launched',BUILDING:'In development',EXPLORING:'Exploring',PAUSED:'Paused'}
  }
};
