export const productSite = 'https://lingoslide.vercel.app/';

export const lingoCaseContent = {
  ru: {
    label: 'СОБСТВЕННЫЙ ПРОДУКТ / PRODUCT DESIGN + AI DELIVERY',
    title: 'LingoSlide — мой продукт от идеи до релиза.',
    lead: 'За месяц личная потребность превратилась в образовательное приложение. Я определил продуктовую концепцию, спроектировал логику обучения и все взаимодействия, отрисовал интерфейс и довёл обновление до релиза.',
    site: 'Открыть сайт продукта', store: 'Смотреть в RuStore', status: 'Версия 1.1.0 опубликована',
    facts: [['34 дня','от идеи до второй версии'],['5000','слов от A1 до C1'],['16','нативных языковых направлений'],['240 / 240','Flutter-тестов прошли']],
    ownershipLabel: 'РОЛИ И ОТВЕТСТВЕННОСТЬ', ownershipTitle: 'Я проектировал продукт. Codex выступал разработчиком.',
    ownershipText: 'Я сформулировал задачу, выбрал образовательную модель и спроектировал путь пользователя. Codex работал со мной как разработчик: исследовал Flutter-код, реализовывал мои решения, проводил рефакторинг и помогал доводить сборки до production.',
    roles: [
      ['Сергей Остаев','Product owner · Product designer','Требования, логика обучения, пользовательские сценарии, UX/UI, приоритеты и приёмка результата.'],
      ['Codex','Разработчик · Technical delivery','Реализация во Flutter, работа с архитектурой и данными, рефакторинг, исправление регрессий, тесты и production-сборки.'],
    ],
    scope: [
      ['Продуктовая концепция','Определил полезный первый сценарий и границы MVP.'],
      ['Логика обучения','Связал новые слова, активное вспоминание, SRS и контрольные точки.'],
      ['UX и взаимодействия','Продумал состояния, переходы, возврат к незавершённому занятию и следующий шаг.'],
      ['UI-система','Отрисовал экраны и собрал единый LS UI-kit для всего приложения.'],
      ['Локализация','Спроектировал работу контента, RTL и языковых вариантов без потери прогресса.'],
      ['Качество релиза','Задал критерии, проверил миграции, тесты и production-сборки.'],
    ],
    problemLabel: '01 / ОТПРАВНАЯ ТОЧКА', problemTitle: 'Слова забывались между занятиями.',
    problemText: 'Грамматическая база уже была, но для живого общения не хватало слов. Нужен был короткий ежедневный сценарий: открыть приложение, выучить несколько слов и без усилий вернуться к ним позже. Я начал с этой собственной задачи, а затем превратил решение в продукт для других пользователей.',
    modelLabel: '02 / ОБРАЗОВАТЕЛЬНАЯ СИСТЕМА', modelTitle: 'Каждое действие связано с дальнейшим обучением.',
    modelText: 'Learning Path ведёт от A1 до C1. Новые слова проходят через знакомство, активное вспоминание и повторение. Сложные слова возвращаются в очередь, а прогресс сохраняется до точного шага незавершённой сессии.',
    modelSteps: ['Знакомство','Вспоминание','Самооценка','Повторение','Контрольная точка'],
    screenNames: {language:'Выбор языка',placement:'Определение уровня',path:'Учебный путь',grammar:'Грамматика'},
    designLabel: '03 / UX/UI', designTitle: 'Рабочую логику превратил в спокойный и понятный интерфейс.',
    designText: 'Я переработал Home, Learning Path, Practice, Grammar, Hints и Profile. В новой системе яснее визуальная иерархия, состояние обучения и следующий шаг. Стикеры поддерживают эмоцию, но не мешают учиться.', designCaption: 'Один из сценариев до и после редизайна',
    processLabel: '04 / КАК Я СОБИРАЛ ПРОДУКТ', processTitle: 'Сценарий, реализация, проверка, улучшение.',
    processText: 'Я проверял экраны в работающем приложении, а не только в макетах. Фиксировал ограничения, ставил задачи небольшими этапами и принимал результат после проверки сценария. Для рискованных изменений сохранял точки возврата.', processCaption: 'Процесс создания: продуктовые решения оставались на моей стороне',
    scaleLabel: '05 / СЛОЖНОСТЬ ПОД КАПОТОМ', scaleTitle: 'Редизайн сохранил данные и учебный прогресс.',
    scaleText: 'Обновление развивало уже работающее приложение. Нужно было сохранить идентификаторы слов, схему базы, SRS, избранное, прогресс по уровням и незавершённые занятия. Смена языка тоже не должна была сбрасывать состояние пользователя.',
    scaleFacts: [['1369','узлов Learning Path'],['43','урока грамматики'],['52704','целевых языковых значения'],['64','production-бандла']],
    proofLabel: '06 / РЕЛИЗ', proofTitle: 'Проект прошёл путь до production.',
    proofText: 'Финальная версия прошла статический анализ, 240 Flutter-тестов, проверку миграций и runtime smoke на Android API 36. Сборки APK и Android App Bundle проверены отдельно. Версия 1.1.0 опубликована в Google Play и RuStore.',
    resultLabel: 'ИТОГ', resultTitle: 'Один человек может отвечать за продукт целиком.',
    resultText: 'LingoSlide показал мой рабочий подход: разобраться в системе, принять продуктовые решения, спроектировать опыт и довести изменения до выпуска. AI расширил мои технические возможности, но направление, критерии и ответственность за результат оставались у меня.', galleryCaption: 'Актуальные экраны LingoSlide 1.1.0',
  },
  en: {
    label: 'OWN PRODUCT / PRODUCT DESIGN + AI DELIVERY', title: 'LingoSlide. From idea to release.',
    lead: 'In one month, a personal need became a learning app. I defined the product concept, designed the learning logic and every interaction, created the interface and took the update through release.',
    site: 'Open the product website', store: 'View on RuStore', status: 'Version 1.1.0 released',
    facts: [['34 days','from idea to version two'],['5,000','words from A1 to C1'],['16','native language tracks'],['240 / 240','Flutter tests passed']],
    ownershipLabel: 'ROLES AND RESPONSIBILITY', ownershipTitle: 'I designed the product. Codex worked as the developer.',
    ownershipText: 'I framed the problem, selected the learning model and designed the user journey. Codex worked with me as the developer: exploring the Flutter codebase, implementing my decisions, refactoring the system and helping take production builds through verification.',
    roles: [
      ['Sergey Ostaev','Product owner · Product designer','Requirements, learning logic, user flows, UX/UI, priorities and final acceptance.'],
      ['Codex','Developer · Technical delivery','Flutter implementation, architecture and data work, refactoring, regression fixes, tests and production builds.'],
    ],
    scope: [
      ['Product concept','Defined the useful first scenario and MVP boundaries.'],
      ['Learning logic','Connected new words, active recall, SRS and checkpoints.'],
      ['UX and interactions','Designed states, transitions, session recovery and the next action.'],
      ['UI system','Designed the screens and a consistent LS UI kit.'],
      ['Localization','Designed content, RTL and locale behavior without losing progress.'],
      ['Release quality','Set the criteria and checked migrations, tests and production builds.'],
    ],
    problemLabel: '01 / STARTING POINT', problemTitle: 'Words disappeared between lessons.',
    problemText: 'The grammar foundation was already there, but everyday conversation needed a larger vocabulary. The core use case had to be short: open the app, learn a few words and return later without friction. I began with that personal need and developed it into a product for other learners.',
    modelLabel: '02 / LEARNING SYSTEM', modelTitle: 'Every action supports the next learning step.',
    modelText: 'The Learning Path runs from A1 to C1. New words move through introduction, active recall and review. Difficult words return to the queue, while the app restores an unfinished session at the exact step.',
    modelSteps: ['Introduction','Active recall','Self assessment','Review','Checkpoint'],
    screenNames: {language:'Choose a language',placement:'Find your level',path:'Learning Path',grammar:'Grammar'},
    designLabel: '03 / UX/UI', designTitle: 'I turned working logic into a calm, clear interface.',
    designText: 'I redesigned Home, Learning Path, Practice, Grammar, Hints and Profile. The new system clarifies hierarchy, learning state and the next action. Stickers add warmth without getting in the way.', designCaption: 'One flow before and after the redesign',
    processLabel: '04 / HOW I BUILT IT', processTitle: 'Scenario, implementation, review, improvement.',
    processText: 'I checked screens in the running app, not only in mockups. I documented constraints, split work into small steps and accepted results after testing the scenario. Risky changes had rollback checkpoints.', processCaption: 'The product decisions remained mine throughout the process',
    scaleLabel: '05 / COMPLEXITY UNDER THE SURFACE', scaleTitle: 'The redesign preserved data and learning progress.',
    scaleText: 'The update evolved an existing app. Stable word IDs, the database schema, SRS, favourites, level progress and unfinished sessions had to remain intact. Switching language also had to preserve user state.',
    scaleFacts: [['1,369','Learning Path nodes'],['43','grammar lessons'],['52,704','localized target values'],['64','production bundles']],
    proofLabel: '06 / RELEASE', proofTitle: 'The project reached production.',
    proofText: 'The final release passed static analysis, 240 Flutter tests, migration checks and an Android API 36 runtime smoke test. APK and Android App Bundle builds were verified separately. Version 1.1.0 is published for Google Play and RuStore.',
    resultLabel: 'OUTCOME', resultTitle: 'One person can own the whole product.',
    resultText: 'LingoSlide demonstrates how I work: understand the system, make product decisions, design the experience and take changes through release. AI expanded my technical reach, while direction, acceptance criteria and responsibility stayed with me.', galleryCaption: 'Current LingoSlide 1.1.0 screens',
  },
};
