export const archiveNavigation = [
  { slug: "studio", icon: "pi-briefcase", ru: "Обзор", en: "Overview" },
  { slug: "flexi", icon: "pi-car", ru: "Flexi", en: "Flexi" },
  { slug: "web", icon: "pi-globe", ru: "Сайты", en: "Websites" },
  { slug: "logos", icon: "pi-palette", ru: "Айдентика", en: "Identity" },
  { slug: "cards", icon: "pi-shopping-bag", ru: "Карточки", en: "Product cards" },
  { slug: "cases", icon: "pi-hashtag", ru: "Соцсети", en: "Social media" },
  { slug: "posts", icon: "pi-megaphone", ru: "Контент", en: "Content" },
  { slug: "print", icon: "pi-file-edit", ru: "Полиграфия", en: "Print" },
];

const gallery = (folder, items) => items.map(([file, ru, en, wide = false]) => ({
  src: `/archive-assets/${folder}/${file}.jpg`,
  ru,
  en,
  wide,
}));

export const archivePages = {
  studio: {
    icon: "pi-briefcase",
    gallery: [
      { src: "/archive-assets/real/taxi-aggregator.jpg", ru: "Taxi Aggregator: UX/UI кейс", en: "Taxi Aggregator: UX/UI case", wide: true },
      { src: "/archive-assets/real/coffee-service.jpg", ru: "VK-оформление сервиса кофемашин", en: "VK packaging for coffee-machine service" },
      { src: "/archive-assets/real/generator-repair.jpg", ru: "VK-группа ремонта генераторов", en: "VK community for generator repair" },
      { src: "/archive-assets/real/fitness-trainer.jpg", ru: "VK-оформление фитнес-инструктора", en: "VK packaging for a fitness instructor" },
      { src: "/archive-assets/real/doctor-balance.jpg", ru: "Доктор баланс: логотип и карточка бренда", en: "Doctor Balance: logo and brand card" },
      { src: "/archive-assets/flexi/08.jpg", ru: "Flexi: продуктовая концепция", en: "Flexi: product concept", wide: true },
      { src: "/archive-assets/web/08.jpg", ru: "Lang.expert: образовательная платформа", en: "Lang.expert: education platform" },
      { src: "/archive-assets/logos/01.jpg", ru: "DOSKI: логотип и носители", en: "DOSKI: logo and applications" },
      { src: "/archive-assets/cards/06.jpg", ru: "Коммерческая графика", en: "Commercial visuals" },
      { src: "/archive-assets/print/01.jpg", ru: "Материалы IT Camp", en: "IT Camp materials", wide: true },
    ],
    ru: {
      eyebrow: "SO Creative / независимый архив",
      title: "Так же, я делаю: сайты, брендинг, соцсети и коммерческую упаковку",
      lead: "Здесь собраны реальные проекты SO Creative, которые дополняют продуктовый дизайн: VK-упаковка, визуальные системы, лендинги, карточки, логотипы и материалы для продаж. Это показывает, что я умею мыслить не только экраном интерфейса, но и всей точкой контакта с клиентом.",
      meta: "2019—2026 / реальные коммерческие проекты",
      metrics: [["5", "реальных ссылок"], ["7", "направлений"], ["50+", "карточек"], ["6+", "лет практики"]],
      storyTitle: "Один подход — разные носители",
      story: [
        "Я начинаю не с декоративного приёма, а с задачи: что человек должен понять, почувствовать и сделать после контакта с дизайном.",
        "Поэтому даже небольшой баннер или карточка товара строятся как продукт: ясная иерархия, сильное обещание, логика сценария и визуальная система, которую можно развивать дальше.",
      ],
      capabilities: [
        ["От идеи до системы", "Исследование контекста, концепция, визуальный язык, набор носителей и правила масштабирования."],
        ["Коммерческий фокус", "Дизайн помогает быстрее считать предложение, отличать бренд и вести пользователя к целевому действию."],
        ["AI в производстве", "Использую нейросети для исследований, вариантов композиции, визуальных прототипов и ускорения контентного цикла."],
      ],
      worksTitle: "Что находится в архиве",
      works: ["Flexi и Taxi Aggregator — UX/UI концепции транспортных сервисов", "Сайты Lang.expert, SUPSURF, Lunara и Geely", "VK-упаковка: кофемашины, ремонт генераторов, фитнес-инструктор и SO Creative", "Айдентика DOSKI, ЗАгоры, QuantumFlow, PRAGMATICA, Cozy Food и Доктор баланс", "Карточки для OZON, Wildberries, Яндекс Маркета и Авито", "Буклет IT Camp, Harmony Fest и редакционные макеты"],
      realCasesTitle: "Работы, которые можно открыть и проверить",
      realCasesText: "Эти проекты ведут на живые страницы или опубликованные кейсы. Их удобно показывать клиентам как доказательство, что дизайн работает в реальном контексте, а не только в презентации.",
      realCases: [
        {
          title: "Ремонт кофемашин",
          type: "VK / сервисная упаковка",
          text: "Оформление сообщества для локального сервиса: обложка, аватар, визуальный тон и быстрый вход в услугу.",
          href: "https://vk.ru/coffee_service63",
          image: "/archive-assets/real/coffee-service.jpg",
          icon: "pi-comments",
        },
        {
          title: "Taxi Aggregator App",
          type: "Behance / UX/UI",
          text: "Продуктовый UX/UI-кейс для агрегатора такси: сценарии, структура, визуальная система и мобильный интерфейс.",
          href: "https://www.behance.net/gallery/245061659/Taxi-Aggregator-App-UX-UI-Case-Study",
          image: "/archive-assets/real/taxi-aggregator.jpg",
          icon: "pi-car",
        },
        {
          title: "Ремонт генераторов",
          type: "VK / оформление группы",
          text: "Коммерческая упаковка группы: понятная категория, доверительный визуал и быстрый сигнал о специализации.",
          href: "https://vk.ru/starter.alternator",
          image: "/archive-assets/real/generator-repair.jpg",
          icon: "pi-wrench",
        },
        {
          title: "Фитнес-инструктор",
          type: "VK / личный бренд",
          text: "Оформление для эксперта: спортивный характер, навигация и визуальная подача услуг в соцсети.",
          href: "https://vk.ru/roslytrener",
          image: "/archive-assets/real/fitness-trainer.jpg",
          icon: "pi-heart",
        },
        {
          title: "Доктор баланс",
          type: "Yandex / айдентика",
          text: "Логотип и брендовый знак для направления, где важны доверие, спокойствие и медицинская аккуратность.",
          href: "https://yandex.ru/profile/209709154475?lang=ru&utm_source=copy_link&utm_medium=social&utm_campaign=share",
          image: "/archive-assets/real/doctor-balance.jpg",
          icon: "pi-sparkles",
        },
      ],
      galleryTitle: "Избранные работы",
    },
    en: {
      eyebrow: "SO Creative / independent archive",
      title: "I also design websites, brands, social media systems, and commercial packaging",
      lead: "This section collects real SO Creative projects that extend my product-design work: VK packaging, visual systems, landing pages, marketplace cards, logos, and sales materials. It shows that I think beyond a single screen and can shape the full customer touchpoint.",
      meta: "2019—2026 / real commercial projects",
      metrics: [["5", "live links"], ["7", "disciplines"], ["50+", "product cards"], ["6+", "years in practice"]],
      storyTitle: "One approach across many formats",
      story: [
        "I begin with the job the design needs to perform: what a person should understand, feel, and do after seeing it.",
        "That is why even a compact banner or marketplace card is treated as a product: clear hierarchy, a strong promise, scenario logic, and a visual system that can grow.",
      ],
      capabilities: [
        ["From idea to system", "Context research, concept, visual language, applications, and rules for scaling."],
        ["Commercial focus", "Design makes the offer easier to read, the brand easier to recognise, and the next action obvious."],
        ["AI-assisted production", "I use neural tools for research, composition studies, visual prototyping, and faster content cycles."],
      ],
      worksTitle: "Inside the archive",
      works: ["Flexi and Taxi Aggregator UX/UI mobility concepts", "Websites for Lang.expert, SUPSURF, Lunara, and Geely", "VK packaging for coffee-machine service, generator repair, fitness instructor, and SO Creative", "Identity for DOSKI, Zagory, QuantumFlow, PRAGMATICA, Cozy Food, and Doctor Balance", "Cards for Ozon, Wildberries, Yandex Market, and Avito", "IT Camp brochure, Harmony Fest, and editorial layouts"],
      realCasesTitle: "Published work you can open and verify",
      realCasesText: "These projects link to live pages or published cases. They work as proof that the design exists in a real context, not only in a presentation.",
      realCases: [
        {
          title: "Coffee-machine service",
          type: "VK / service packaging",
          text: "Community packaging for a local repair service: cover, avatar, visual tone, and fast entry into the offer.",
          href: "https://vk.ru/coffee_service63",
          image: "/archive-assets/real/coffee-service.jpg",
          icon: "pi-comments",
        },
        {
          title: "Taxi Aggregator App",
          type: "Behance / UX/UI",
          text: "A product UX/UI case for a taxi aggregator: scenarios, structure, visual system, and mobile interface.",
          href: "https://www.behance.net/gallery/245061659/Taxi-Aggregator-App-UX-UI-Case-Study",
          image: "/archive-assets/real/taxi-aggregator.jpg",
          icon: "pi-car",
        },
        {
          title: "Generator repair",
          type: "VK / community design",
          text: "Commercial community packaging with a clear category signal, trust-oriented visuals, and service focus.",
          href: "https://vk.ru/starter.alternator",
          image: "/archive-assets/real/generator-repair.jpg",
          icon: "pi-wrench",
        },
        {
          title: "Fitness instructor",
          type: "VK / personal brand",
          text: "Packaging for an expert profile: active tone, navigation, and a clear service presentation.",
          href: "https://vk.ru/roslytrener",
          image: "/archive-assets/real/fitness-trainer.jpg",
          icon: "pi-heart",
        },
        {
          title: "Doctor Balance",
          type: "Yandex / identity",
          text: "Logo and brand mark for a direction where trust, calmness, and medical clarity matter.",
          href: "https://yandex.ru/profile/209709154475?lang=ru&utm_source=copy_link&utm_medium=social&utm_campaign=share",
          image: "/archive-assets/real/doctor-balance.jpg",
          icon: "pi-sparkles",
        },
      ],
      galleryTitle: "Selected work",
    },
  },
  flexi: {
    icon: "pi-car",
    gallery: gallery("flexi", [
      ["08", "Экосистема Flexi", "Flexi ecosystem", true],
      ["02", "Ключевые пользовательские сценарии", "Core user journeys", true],
      ["03", "Технические и сервисные сценарии", "Technical and service flows", true],
      ["07", "Интерфейс выбора поездки", "Ride selection interface", true],
      ["12", "Продукт в городской среде", "Product in an urban context"],
      ["13", "Визуальная презентация концепции", "Visual concept presentation"],
    ]),
    ru: {
      eyebrow: "Продуктовая концепция / Mobility",
      title: "Flexi — агрегатор такси нового поколения",
      lead: "Мультиоператорская платформа, где пользователь сначала выбирает подходящий тариф, а затем сравнивает операторов по цене, времени подачи и надёжности.",
      meta: "2026 / исследование, UX, UI, бренд-система",
      metrics: [["3 нед.", "концепция и визуальная система"], ["2 нед.", "UX и интерфейс"], ["1", "единый контур выбора"], ["MVP", "готовая модель запуска"]],
      storyTitle: "Новый слой принятия решения",
      story: [
        "Рынок перенасыщен операторами: люди открывают несколько приложений и вручную сравнивают стоимость и время подачи. Проблема находится не в заказе автомобиля, а в выборе между множеством непрозрачных предложений.",
        "Я изменил точку входа в сценарий: сначала сегмент поездки, затем сравнение операторов внутри него. Это снижает когнитивную нагрузку и делает ценообразование понятнее.",
      ],
      capabilities: [
        ["Моя роль", "Инициатор концепции и ведущий продуктовый дизайнер: продуктовое видение, бренд-стратегия, UX-архитектура и ключевые решения."],
        ["Принцип", "Оптимальный баланс цены, времени подачи и надёжности важнее привычки пользоваться одним приложением."],
        ["Система", "Рациональный городской бренд, масштабируемые компоненты и сценарии для разных тарифов и операторов."],
      ],
      worksTitle: "Что было спроектировано",
      works: ["Анализ рынка и продуктовая гипотеза", "Позиционирование и характер бренда", "Карта сценариев и архитектура сервиса", "Выбор тарифа и сравнение операторов", "Авторизация, поиск, заказ и статус поездки", "Компонентная UI-система и презентация MVP"],
      galleryTitle: "От логики к интерфейсу",
    },
    en: {
      eyebrow: "Product concept / Mobility",
      title: "Flexi — a next-generation taxi aggregator",
      lead: "A multi-operator platform where users choose a fare category first, then compare providers by price, arrival time, and reliability.",
      meta: "2026 / research, UX, UI, brand system",
      metrics: [["3 weeks", "concept and visual system"], ["2 weeks", "UX and interface"], ["1", "decision layer"], ["MVP", "launch-ready model"]],
      storyTitle: "A new decision layer",
      story: [
        "The market is crowded with operators, so people open several apps and manually compare price and arrival time. The real friction is not ordering a car, but choosing between opaque offers.",
        "I changed the entry point: first select the ride segment, then compare operators within it. This reduces cognitive load and makes pricing more transparent.",
      ],
      capabilities: [
        ["My role", "Concept initiator and lead product designer responsible for product vision, brand strategy, UX architecture, and key decisions."],
        ["Core principle", "The best balance of price, arrival time, and reliability matters more than loyalty to a single app."],
        ["System", "A rational urban brand, scalable components, and journeys for multiple fare types and providers."],
      ],
      worksTitle: "What I designed",
      works: ["Market analysis and product hypothesis", "Positioning and brand character", "Journey map and service architecture", "Fare selection and provider comparison", "Authentication, search, order, and ride status", "Component UI system and MVP presentation"],
      galleryTitle: "From logic to interface",
    },
  },
  web: {
    icon: "pi-globe",
    gallery: gallery("web", [
      ["08", "Lang.expert — главная страница", "Lang.expert — home page", true],
      ["01", "Lang.expert — адаптивные состояния", "Lang.expert — responsive states"],
      ["02", "SUPSURF — продуктовый лендинг", "SUPSURF — product landing page"],
      ["04", "Lunara — цифровая атмосфера", "Lunara — digital atmosphere"],
      ["06", "Структура образовательной платформы", "Education platform structure"],
      ["07", "Lunara — сценарий знакомства", "Lunara — onboarding story"],
      ["10", "SUPSURF — каталог и доверие", "SUPSURF — catalogue and trust"],
    ]),
    ru: {
      eyebrow: "Веб-дизайн / лендинги",
      title: "Сайты, где визуал поддерживает сценарий",
      lead: "Проектирую структуру, пользовательский путь и финальный UI так, чтобы посетитель быстро понял предложение и дошёл до действия без лишних остановок.",
      meta: "Figma / Tilda / адаптивный дизайн",
      metrics: [["4", "разных рынка"], ["Desktop", "и mobile"], ["UX", "до визуала"], ["CTA", "в центре сценария"]],
      storyTitle: "Сначала логика, потом эстетика",
      story: ["Каждый проект начинался со структуры: аудитория, обещание, аргументы доверия, продуктовые блоки и целевое действие.", "После этого я собирал визуальный ритм, адаптивные состояния и передавал готовую систему для публикации или разработки."],
      capabilities: [["Lang.expert", "Сайт языковой школы с программами, бесплатным уроком, отзывами и понятной воронкой записи."], ["SUPSURF", "Каталог сапбордов, преимущества продукта, доверие и быстрый путь к покупке."], ["Lunara и Geely", "Презентационный digital-опыт: от атмосферы приложения до коммерческого автомобильного лендинга."]],
      worksTitle: "Состав работы",
      works: ["Исследование конкурентов и референсов", "Информационная архитектура", "Прототип ключевых блоков", "Визуальная концепция", "Desktop и mobile состояния", "Подготовка к Tilda или передаче в разработку"],
      galleryTitle: "Четыре продукта — четыре визуальных языка",
    },
    en: {
      eyebrow: "Web design / landing pages",
      title: "Websites where visuals support the journey",
      lead: "I design structure, user flow, and final UI so visitors understand the offer quickly and reach the intended action without friction.",
      meta: "Figma / Tilda / responsive design",
      metrics: [["4", "different markets"], ["Desktop", "and mobile"], ["UX", "before styling"], ["CTA", "at the centre"]],
      storyTitle: "Logic first, aesthetics second",
      story: ["Every project began with the structure: audience, promise, trust signals, product blocks, and target action.", "I then built the visual rhythm, responsive states, and a system ready for publishing or development."],
      capabilities: [["Lang.expert", "A language-school website with programmes, a free lesson, testimonials, and a clear registration funnel."], ["SUPSURF", "A paddle-board catalogue balancing product benefits, trust, and a short path to purchase."], ["Lunara and Geely", "Presentation-led digital experiences, from a meditation app atmosphere to a commercial automotive landing page."]],
      worksTitle: "Scope",
      works: ["Competitor and reference research", "Information architecture", "Key-block wireframes", "Visual concept", "Desktop and mobile states", "Tilda implementation or developer handoff"],
      galleryTitle: "Four products, four visual languages",
    },
  },
  logos: {
    icon: "pi-palette",
    gallery: gallery("logos", [
      ["01", "DOSKI — премиальная система носителей", "DOSKI — premium application system", true],
      ["03", "Доктор Баланс — упаковка продукта", "Doctor Balance — product packaging"],
      ["04", "ЗАгоры — айдентика эко-отеля", "Zagory — eco-hotel identity"],
      ["07", "QuantumFlow — технологический бренд", "QuantumFlow — technology brand"],
      ["08", "PRAGMATICA — строительная компания", "PRAGMATICA — construction company"],
      ["06", "DOSKI — масштабирование знака", "DOSKI — mark in use"],
      ["14", "Cozy Food — кулинарный медиа-бренд", "Cozy Food — culinary media brand"],
    ]),
    ru: {
      eyebrow: "Логотипы / фирменный стиль",
      title: "Айдентика, которая начинается со смысла",
      lead: "Не рисую знак в вакууме: проверяю, как идея живёт на упаковке, вывеске, мерче, в соцсетях и маленькой иконке.",
      meta: "7 брендов / логотипы и носители",
      metrics: [["7", "бренд-систем"], ["B2B", "и consumer"], ["Digital", "и печать"], ["Scale", "от иконки до вывески"]],
      storyTitle: "Знак — это начало системы",
      story: ["В основе каждого проекта — характер бизнеса, контекст рынка и ассоциация, которую бренд должен закрепить.", "Форма проходит проверку на читаемость, масштабирование и работу на реальных носителях, поэтому результат можно развивать, а не перерисовывать заново."],
      capabilities: [["Стратегический образ", "Фиксирую характер и смысл бренда до поиска формы."], ["Система носителей", "Показываю, как знак работает на упаковке, мерче, фасаде и digital-поверхностях."], ["Готовность к росту", "Цвет, типографика и правила применения поддерживают будущий брендинг."]],
      worksTitle: "Бренды в подборке",
      works: ["Доктор Баланс — здоровое питание и БАДы", "DOSKI — лестницы под ключ", "ЗАгоры — эко-отель и глэмпинг", "Рыбное место — ресторан морепродуктов", "QuantumFlow — интеграционные IT-решения", "PRAGMATICA — строительная компания", "Cozy Food — кулинарный канал"],
      galleryTitle: "Знаки в реальном контексте",
    },
    en: {
      eyebrow: "Logos / visual identity",
      title: "Identity built from meaning",
      lead: "I never design a mark in isolation. I test how the idea works on packaging, signage, merchandise, social media, and at icon size.",
      meta: "7 brands / logos and applications",
      metrics: [["7", "identity systems"], ["B2B", "and consumer"], ["Digital", "and print"], ["Scale", "icon to signage"]],
      storyTitle: "The mark is the beginning of a system",
      story: ["Each project starts with business character, market context, and the association the brand needs to own.", "The form is tested for legibility, scale, and real applications, creating an identity that can grow rather than be redrawn."],
      capabilities: [["Strategic image", "I define the brand's character and meaning before exploring form."], ["Application system", "The mark is tested across packaging, merchandise, signage, and digital surfaces."], ["Built to grow", "Colour, typography, and usage principles support future brand development."]],
      worksTitle: "Brands in this collection",
      works: ["Doctor Balance — nutrition and supplements", "DOSKI — bespoke staircases", "Zagory — eco-hotel and glamping", "Rybnoe Mesto — seafood restaurant", "QuantumFlow — IT integration solutions", "PRAGMATICA — construction company", "Cozy Food — culinary channel"],
      galleryTitle: "Marks in real contexts",
    },
  },
  cards: {
    icon: "pi-shopping-bag",
    gallery: gallery("cards", [
      ["01", "Игрушка для собак — оффер и преимущества", "Dog toy — offer and benefits"],
      ["02", "Патчи — сценарий использования", "Eye patches — usage story"],
      ["04", "Автокомпрессор — аргументы выбора", "Car compressor — reasons to choose"],
      ["06", "Сервис кофемашин — карточка услуги", "Coffee-machine service card", true],
      ["07", "SUP board — эмоциональная обложка", "SUP board — emotional cover"],
      ["08", "Ремонт стартеров — чистая продуктовая подача", "Starter repair — clean product story", true],
      ["09", "Патчи — premium-визуал", "Eye patches — premium visual"],
      ["12", "SUP board — характеристики", "SUP board — specifications", true],
    ]),
    ru: {
      eyebrow: "Marketplace / коммерческая графика",
      title: "Карточки, которые объясняют товар за секунды",
      lead: "Соединяю иерархию, маркетинговый аргумент и предметный визуал, чтобы карточка останавливала взгляд и помогала принять решение.",
      meta: "OZON / Wildberries / Яндекс Маркет / Авито",
      metrics: [["50+", "карточек"], ["12+", "брендов"], ["4", "площадки"], ["6+", "лет опыта"]],
      storyTitle: "Не украшение, а короткая продающая история",
      story: ["На первом экране фиксирую категорию, главное преимущество и визуальный якорь. Следующие карточки снимают сомнения: характеристики, сценарии, комплектация и доверие.", "Для услуг на Авито логика похожа, но вместо товара продаётся понятный процесс и уверенность в результате."],
      capabilities: [["Быстрое считывание", "Ключевой оффер виден даже в маленьком превью поисковой выдачи."], ["Аргументация", "Каждый слайд отвечает на конкретный вопрос или возражение покупателя."], ["Серийность", "Система масштабируется на линейку товаров и сезонные обновления."]],
      worksTitle: "Категории",
      works: ["Игрушка-мяч для собак", "Автомобильный компрессор 12V", "Освежающие патчи для глаз", "SUP board для летних прогулок", "Ремонт стартеров и генераторов", "Ремонт и обслуживание кофемашин"],
      galleryTitle: "Из выдачи — в карточку товара",
    },
    en: {
      eyebrow: "Marketplaces / commercial graphics",
      title: "Product cards that explain value in seconds",
      lead: "I combine hierarchy, a marketing argument, and product-focused visuals to stop the scroll and help people decide.",
      meta: "Ozon / Wildberries / Yandex Market / Avito",
      metrics: [["50+", "product cards"], ["12+", "brands"], ["4", "platforms"], ["6+", "years"]],
      storyTitle: "Not decoration, but a compact sales story",
      story: ["The first frame establishes category, primary benefit, and a visual anchor. The following frames resolve doubts with specifications, use cases, contents, and trust signals.", "Service listings follow the same logic, but sell a clear process and confidence in the outcome."],
      capabilities: [["Fast scanning", "The core offer remains legible even in a small search thumbnail."], ["Argument structure", "Every slide answers one buyer question or objection."], ["Scalable series", "The visual system expands across product lines and seasonal updates."]],
      worksTitle: "Categories",
      works: ["Dog ball toy", "12V car compressor", "Refreshing eye patches", "Summer SUP board", "Starter and alternator repair", "Coffee-machine repair and maintenance"],
      galleryTitle: "From search results to product detail",
    },
  },
  cases: {
    icon: "pi-hashtag",
    gallery: gallery("cases", [
      ["02", "Onyx Bank — визуальная система", "Onyx Bank — visual system", true],
      ["06", "Сообщество в мобильном контексте", "Community in a mobile context", true],
      ["05", "Полная лента и рубрикатор", "Full feed and content system"],
      ["07", "Редизайн сообщества", "Community redesign"],
      ["09", "Профиль как единая витрина", "Profile as a unified storefront"],
      ["12", "Длинная презентация кейса", "Long-form case presentation"],
      ["01", "Рекламный визуал", "Campaign visual"],
    ]),
    ru: {
      eyebrow: "Соцсети / упаковка сообществ",
      title: "Сообщество как цельный цифровой продукт",
      lead: "Оформляю не набор обложек, а систему: позиционирование, навигацию, рубрики, шаблоны контента и единый визуальный ритм.",
      meta: "VK / Instagram / рекламные форматы",
      metrics: [["System", "вместо разовых макетов"], ["Mobile", "проверка ленты"], ["Content", "рубрики и шаблоны"], ["Trust", "единый образ бренда"]],
      storyTitle: "Упаковка должна помогать ориентироваться",
      story: ["Пользователь видит аватар, обложку, меню и первые публикации почти одновременно. Поэтому я связываю их общей иерархией и обещанием бренда.", "Шаблоны дают команде свободу выпускать новый контент без потери качества, а сообщество начинает работать как узнаваемая витрина."],
      capabilities: [["Аудит и позиционирование", "Определяю, что должно быть понятно человеку в первые секунды."], ["Навигация и рубрики", "Структурирую путь от знакомства до нужного раздела или обращения."], ["Контентная система", "Создаю шаблоны, которые выдерживают регулярный выпуск материалов."]],
      worksTitle: "Что входит в направление",
      works: ["Аватар и адаптивная обложка", "Меню и навигационные карточки", "Визуальная сетка сообщества", "Шаблоны постов и рекламных материалов", "Хайлайты и сторис", "Презентация логики для команды"],
      galleryTitle: "Система в ленте и на носителях",
    },
    en: {
      eyebrow: "Social media / community packaging",
      title: "A community designed as one digital product",
      lead: "I build more than a set of covers: positioning, navigation, recurring formats, content templates, and one consistent visual rhythm.",
      meta: "VK / Instagram / campaign formats",
      metrics: [["System", "not isolated assets"], ["Mobile", "feed validation"], ["Content", "formats and templates"], ["Trust", "one brand image"]],
      storyTitle: "Packaging should help people navigate",
      story: ["People see the avatar, cover, menu, and first posts almost at once, so I connect them through one hierarchy and brand promise.", "Templates let teams publish regularly without losing quality, turning a community into a recognisable storefront."],
      capabilities: [["Audit and positioning", "I define what a person must understand in the first few seconds."], ["Navigation and formats", "I structure the path from first contact to a relevant section or enquiry."], ["Content system", "I create templates that remain consistent through regular publishing."]],
      worksTitle: "Scope",
      works: ["Avatar and responsive cover", "Menu and navigation cards", "Community feed system", "Post and campaign templates", "Highlights and stories", "System presentation for the team"],
      galleryTitle: "The system in feeds and applications",
    },
  },
  posts: {
    icon: "pi-megaphone",
    gallery: gallery("posts", [
      ["09", "Серия сторис и постов", "Stories and post series", true],
      ["01", "Динамический сторис-формат", "Dynamic story format"],
      ["03", "Кофейный оффер", "Coffee offer"],
      ["04", "Volna&Code — афиша события", "Volna&Code — event poster"],
      ["06", "Крипто-рубрика", "Crypto content format"],
      ["07", "Точка отсчёта — серия", "Starting Point — series"],
      ["08", "Точка отсчёта — ключевой визуал", "Starting Point — key visual"],
    ]),
    ru: {
      eyebrow: "Контент-дизайн / social",
      title: "Форматы, которые удерживают узнаваемость",
      lead: "Разрабатываю визуальные рубрики для событий, экспертных блогов и коммерческих аккаунтов — от одного анонса до серии постов и сторис.",
      meta: "Посты / сторис / афиши / прогревы",
      metrics: [["Series", "а не одиночный пост"], ["9:16", "и 1:1"], ["Fast", "адаптация форматов"], ["Tone", "под голос бренда"]],
      storyTitle: "Контенту нужен ритм, а не одинаковость",
      story: ["Система задаёт узнаваемые правила — типографику, цвет, композиционный приём, — но оставляет пространство для нового сюжета.", "Так лента выглядит цельно, а команда не застревает в бесконечном копировании одного шаблона."],
      capabilities: [["События", "Анонсы, программа, спикеры и напоминания в одном визуальном языке."], ["Экспертный контент", "Серии для сложных тем: психология, отношения, технологии и финансы."], ["Коммерческие офферы", "Акцент на сроке, выгоде и действии без визуального шума."]],
      worksTitle: "Темы и форматы",
      works: ["Volna&Code — анонсы IT-сообщества", "Good Morning — утреннее предложение кафе", "Crypto-взгляд — образовательная рубрика", "Точка отсчёта — прогрев психологического эфира", "Посты и сторис для коммерческих аккаунтов", "Адаптации под ленту и вертикальный формат"],
      galleryTitle: "Контентные серии",
    },
    en: {
      eyebrow: "Content design / social",
      title: "Formats that preserve recognition",
      lead: "I develop recurring visual formats for events, expert blogs, and commercial accounts, from a single announcement to full post and story series.",
      meta: "Posts / stories / posters / launches",
      metrics: [["Series", "not isolated posts"], ["9:16", "and 1:1"], ["Fast", "format adaptation"], ["Tone", "matched to brand voice"]],
      storyTitle: "Content needs rhythm, not sameness",
      story: ["A system defines recognisable rules for typography, colour, and composition while leaving room for a new story.", "The feed stays coherent without forcing the team to duplicate one template forever."],
      capabilities: [["Events", "Announcements, agenda, speakers, and reminders in one visual language."], ["Expert content", "Series for complex subjects including psychology, relationships, technology, and finance."], ["Commercial offers", "Clear focus on timing, value, and action without visual noise."]],
      worksTitle: "Topics and formats",
      works: ["Volna&Code IT community announcements", "Good Morning cafe offer", "Crypto View educational series", "Starting Point psychology launch", "Posts and stories for commercial accounts", "Feed and vertical adaptations"],
      galleryTitle: "Content series",
    },
  },
  print: {
    icon: "pi-file-edit",
    gallery: gallery("print", [
      ["01", "Буклет IT Camp в использовании", "IT Camp brochure in use", true],
      ["03", "Презентация решения", "Solution presentation", true],
      ["04", "Буклет на мероприятии", "Brochure at the event"],
      ["06", "Разворот буклета", "Brochure spread", true],
      ["07", "Информационная архитектура буклета", "Brochure information architecture", true],
      ["12", "Harmony Fest — городская афиша", "Harmony Fest — city poster", true],
      ["14", "Редакционный разворот", "Editorial spread", true],
    ]),
    ru: {
      eyebrow: "Полиграфия / презентации",
      title: "Дизайн для физического пространства",
      lead: "Буклеты, афиши и редакционные развороты, где важны не только композиция, но и реальный размер, дистанция чтения, печать и контекст события.",
      meta: "Буклеты / постеры / журналы / презентации",
      metrics: [["IT Camp", "всероссийская программа"], ["A4", "и outdoor"], ["Print", "подготовка макетов"], ["Story", "ясная подача проекта"]],
      storyTitle: "Digital-мышление, адаптированное к печати",
      story: ["Печатный носитель нельзя исправить после публикации, поэтому иерархия, поля, контраст и техническая подготовка проверяются до отправки.", "В буклете IT Camp я упаковал сложный технологический проект в короткий маршрут: проблема, решение, визуальные доказательства и QR-переход к деталям."],
      capabilities: [["IT Camp", "Буклет и презентационные материалы для защиты технологического проекта."], ["Harmony Fest", "Афиша, адаптированная для городской поверхности, листовок и соцсетей."], ["Журнал «Выбирай»", "Редакционный разворот о выставке с коллажной композицией и приглушённой палитрой."]],
      worksTitle: "Подготовленные материалы",
      works: ["Буклет IT Camp", "Презентация проекта токовой диагностики", "Афиша Harmony Fest", "Адаптации для наружной рекламы", "Разворот журнала «Выбирай»", "Файлы для печати и digital-публикации"],
      galleryTitle: "От экрана до печатного тиража",
    },
    en: {
      eyebrow: "Print / presentations",
      title: "Design for physical space",
      lead: "Brochures, posters, and editorial spreads where composition works together with real size, reading distance, print constraints, and event context.",
      meta: "Brochures / posters / editorial / presentations",
      metrics: [["IT Camp", "national programme"], ["A4", "and outdoor"], ["Print", "production-ready"], ["Story", "clear project narrative"]],
      storyTitle: "Digital thinking adapted for print",
      story: ["A printed piece cannot be corrected after release, so hierarchy, margins, contrast, and production setup are validated before handoff.", "For the IT Camp brochure I compressed a complex technology project into a short journey: problem, solution, visual evidence, and a QR path to details."],
      capabilities: [["IT Camp", "Brochure and presentation materials for a technology-project pitch."], ["Harmony Fest", "A poster adapted for urban media, handouts, and social channels."], ["Vybiray magazine", "An exhibition spread using collage composition and a restrained colour palette."]],
      worksTitle: "Delivered materials",
      works: ["IT Camp brochure", "Current-diagnostics project presentation", "Harmony Fest poster", "Outdoor advertising adaptations", "Vybiray magazine spread", "Print-ready and digital files"],
      galleryTitle: "From screen to print run",
    },
  },
};

export function getArchivePage(slug) {
  return archivePages[slug] ?? archivePages.studio;
}
